archiva/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'archiva.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^archiva/', include('ingest.urls', namespace='ingest')),
    url(r'^admin/', include(admin.site.urls)),
    
]

ingest/urls.py
from django.conf.urls import url
from ingest import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # archiva/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # archiva/login/
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    # archiva/logout/
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    # archiva/signup/
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),

    # archiva/dashboard/main/id=user_id  HOME DASHBOARD VIEW URL
    url(r'^dashboard/main/id=(?P<id>[0-9]+)$', views.MainDashView.as_view(), name='maindash'),

    url(r'^dashboard/home/id=(?P<id>[0-9]+)$', views.HomeDashView.as_view(), name='homedash'),

    # archiva/dashboard/ingest/id=user_id  INGEST DASHBOARD VIEW
    url(r'^dashboard/ingest/id=(?P<id>[0-9]+)$', views.IngestDashView.as_view(), name='ingestdash'),

    # archiva/dashboard/store/id=user_id
    url(r'^dashboard/store/id=(?P<id>[0-9]+)$', views.StoreDashView.as_view(), name='storedash'),

    # archiva/dashboard/search/id=user_id
    url(r'^dashboard/search/id=(?P<id>[0-9]+)$', views.SearchDashView.as_view(), name='searchdash'),

    # End point urls
    url(r'^repository/create/id=(?P<id>[0-9]+)$', views.CreateRepository.as_view(), name='create'),
    url(r'^allusers/$', views.get_all_users, name='allusers'),
    url(r'^content/id=(?P<id>[0-9]+)$', views.get_repository_content, name='content'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ingest/models.py
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible

from ingest.utils import change_upload_path


# Create your models here.

# User profile information
@python_2_unicode_compatible
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    interest = models.CharField(max_length=100, null=True)
    occupation = models.CharField(max_length=30, null=True)

    # sets the field of interest
    def set_interest(self, interest):
        self.interest = interest

    # sets the occupation
    def set_occupation(self, occupation):
        self.occupation = occupation

    # string representation of the model
    def __str__(self):
        return 'Username: %s, Occupation: %s' % (self.user, self.occupation)


# Keeps track of account logs
@python_2_unicode_compatible
class AccountLog(models.Model):
    acc_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    time_in = models.TimeField()
    time_out = models.TimeField()
    date = models.DateField(null=True)

    # string representation of the Account log
    def __str__(self):
        return 'User: %s, Time in: %s, Time out %s' % (self.acc_user, self.time_in, self.time_out)


# Class represents an archive repository
@python_2_unicode_compatible
class Repository(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    repo_size = models.IntegerField(default=0)
    date_created = models.DateTimeField(auto_now=True)

# Class represents the Archive Content
@python_2_unicode_compatible
class Content(models.Model):
    repo = models.ForeignKey(Repository, on_delete=models.CASCADE, null=True)
    content_name = models.CharField(max_length=100)
    repo_name = models.CharField(max_length=30, null=True)
    file = models.FileField(upload_to=change_upload_path, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # string representation of the content
    def __str__(self):
        return '%s' % self.content_name


# Class represents content metadata
@python_2_unicode_compatible
class ContentMetadata(models.Model):
    content = models.OneToOneField(Content, primary_key=True)
    file_type = models.CharField(max_length=20)
    file_size = models.IntegerField(default=0)
    date_uploaded = models.DateTimeField(auto_now=True)
    meta_tags = models.CharField(max_length=100)
    description = models.TextField()
    permissions = models.TextField()

    # sets meta tags
    def set_meta_tags(self, tags=None):
        if type(tags) != type([]):
            return
        self.meta_tags = ','.join(tags)


# Class to represent uploaded files
class Upload(models.Model):
    title = models.CharField(max_length=40)
    uploaded_file = models.FileField(upload_to=settings.MEDIA_ROOT)

ingest/forms.py
from django import forms
from django.forms import ModelForm

class SignUpForm(forms.Form):   
    firstname = forms.CharField(max_length=25)
    lastname = forms.CharField(max_length=25)
    email = forms.EmailField()
    password = forms.CharField(min_length=8, widget=forms.PasswordInput)
    cpassword = forms.CharField(min_length=8, widget=forms.PasswordInput)
    
class LoginForm(forms.Form):
    username = forms.CharField(max_length=60)
    password = forms.CharField(min_length=8, widget=forms.PasswordInput)    
    
    
class UploadForm(forms.Form):
    title = forms.CharField(max_length=25)
    content = forms.FileField()
    tags = forms.CharField()
    desc = forms.CharField()

class RepositoryForm(forms.Form):
    name =  forms.CharField(max_length=40)

ingest/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse

from .models import Upload
from django.views.generic import View

from ingest.models import Repository, Content, ContentMetadata
from ingest.forms import UploadForm, SignUpForm, RepositoryForm, LoginForm

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from .mixins import LoginRequiredMixin

from ingest.utils import is_file_supported, is_zip, handle_zip_file


# Create your views here.

class IndexView(View):
    # return the homepage
    def get(self, request):
        # logout(request)
        return render(request, 'ingest/index.html')


# Login view
class LoginView(View):
    user = None
    form_class = LoginForm
    template_name = 'ingest/login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'error': ''})

    def post(self, request, *args, **kwargs):
        # create form and populate with login data
        form = self.form_class(request.POST)
        # validate the form
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # authenticate user
            self.user = authenticate(username=username, password=password)
            if self.user is not None:
                if self.user.is_active:
                    request.session.set_expiry(0)
                    login(request, self.user)
                    # set the user id in the session
                    request.session['user_id'] = self.user.id
                    return HttpResponseRedirect(reverse('ingest:maindash', args=(self.user.id,)))
                else:
                    error = 'Account locked'
            else:
                error = 'Invalid username and or password'
        else:
            error = 'Internal error please check back later'

        return render(request, self.template_name, {'error': error})


# User signup view
class SignUpView(View):
    user = None
    template_name = 'ingest/signup.html'
    form_class = SignUpForm

    def get(self, request, *args, **kwargs):
        return render(request, 'ingest/signup.html')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        # validate form inputs
        if form.is_valid():
            data = form.cleaned_data
            if self.pass_equal(data['password'], data['cpassword']):
                self.user = User.objects.create(
                    first_name=data['firstname'],
                    last_name=data['lastname'],
                    username=data['email'])

                # set user password and save to database
                self.user.set_password(data['password'])
                self.user.save()
                return HttpResponseRedirect(reverse('ingest:login'))
            else:
                error = 'Passwords not equal'
        else:
            error = 'There seems to be a problem with your input please check it and try again'
        return render(request, self.template_name, {'error': error})

    """
        Confirms passwords are equal
    """

    def pass_equal(self, pass_one, pass_two):
        if pass_one != pass_two:
            return False
        else:
            return True


"""
    Dashboard Views... All dashboard views
"""


class MainDashView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.user.id != request.session['user_id']:
            return HttpResponseRedirect(reverse('ingest:logout'))
        return render(request, 'ingest/maindash.html', {'user': request.user})


class HomeDashView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'ingest/homedash.html', {'user': request.user})


class IngestDashView(LoginRequiredMixin, View):
    form = UploadForm
    model = Content
    meta = ContentMetadata
    #
    def get(self, request, *args, **kwargs):
        repo = request.user.repository_set.all()
        return render(request, 'ingest/ingestview.html', {'repo': repo})

    #
    def post(self, request, *args, **kwargs):
        form = self.form(request.POST, request.FILES)
        status = dict();

        if form.is_valid():
            repo = None

            # get the uploaded file(s)
            data = form.cleaned_data

            # Get all repositories owned by the user
            repositories = request.user.repository_set.all()

            # Make sure a valid repository is selected
            if data['title'] == 'undefined':
                return JsonResponse({'status': 'Upload error: no repository selected'})

            # We need the repository that matches the one specified by the user
            for r in repositories:
                if r.name == data['title']:
                    repo = r

            # We get the uploaded file
            file = data['content']

            # PERFORM COMPLAINCE CHECKS
            # Check file type
            if is_file_supported(file):
                status['format'] = "passed"
            else:
                status['format'] = 'failed'
                return HttpResponse(file.content_type)

            # Check if file is zip
            if is_zip(file):
                if handle_zip_file(file):
                    status['zipopend'] = "passed"
                    return HttpResponse('Files opened')
                else:
                    return HttpResponse('error opening file')

            # Extract content meta data from file
            met =  dict()
            met['type'] = file.content_type
            met['size'] = file.size
            met['tags'] = data['tags']
            met['desc'] = data['desc']

            # Strip the file extension from the file
            # content_name = f[0:f.find('.')]

            # Save the uploaded file to the specified repository
            content = self.model.objects.create(repo=repo, content_name=file.name, repo_name=data['title'], file=file, owner=request.user)
            content.save()
            content_desc = self.meta.objects.create(content=content, file_type=met['type'], file_size=met['size'],
                                         meta_tags=met['tags'], description=met['desc'])
            if content_desc:
                content_desc.save()
                return HttpResponse('meta sucessfully extracted')
            return HttpResponse('File successfully saved')
        else:
            return HttpResponse('Upload error')


# Upload(IngestView)
class StoreDashView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        # get all repositories belonging to the current user
        repos = request.user.repository_set.all()
        return render(request, 'ingest/storedash.html', {'repos': repos})

    # Handle file uploads from post
    def post(self, request, *args, **kwargs):
        return render(request, '')

# Search (SearchView)
class SearchDashView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'ingest/search.html')

    # Handle file uploads from post
    def post(self, request, *args, **kwargs):
        return render(request, '')

# Logout view
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('ingest:index'))


"""
    Data endpoints
"""


# create repository
class CreateRepository(LoginRequiredMixin, View):
    model = Repository
    form = RepositoryForm

    def post(self, request, *args, **kwargs):
        error = 'form error'

        # need the nuber of repositories created by the current user
        no_of_repos = len(request.user.repository_set.all())

        if no_of_repos >= 3:
            return JsonResponse({'response': 'You have reached your limit'})


        form = self.form(request.POST)
        if form.is_valid():
            repo = self.model.objects.create(owner=request.user, name=form.cleaned_data['name'])
            repo.save()
            return HttpResponse('success')
        else:
            return HttpResponse(error)



# End points
def get_repository_content(request, id):
    from ingest.models import ContentMetadata

    '''if request.is_ajax():
        if request.method == 'GET':
            repo_id = id #request.GET['repo_id']
            repo =  Repository.objects.get(pk=repo_id)
            content = list(repo.content_set.all().values('id', 'content_name'))
            data = list(content)
            response = json.dumps(data)
            return HttpResponse(response, content_type='application/json')
        else:
            return JsonResponse()'''

    if request.method == 'GET':
        repo = Repository.objects.get(pk=id)
        files = repo.content_set.all()

        meta = dict()

        for f in files:
            meta[f.content_name] = ContentMetadata.objects.get(content=f)

        return render(request, 'ingest/repository_file_list.html', {"files": files, 'repository': repo, 'meta':meta})


def get_all_users(request):
    import json
    if request.is_ajax():
        if request.method == 'GET':
            data = list(User.objects.values('first_name', 'last_name', 'username'))
            data = list(data)
            response = json.dumps(data)
            return HttpResponse(response, content_type='application/json')
    else:
        return HttpResponse('Endpoint service link breakage')

ingest/templates/ingest/homedash.html
{% block content %}
<br/>
<article id="view" class="ui center container">
    <div class="ui grid">

        <!-- Begin first row -->

        <div class="one wide column"></div>
        <div class="five wide column">
            <div class="ui inline compact segment home-card" data-id="2">
                <div class="box">
                    <span class="icon icon-cloud-upload home-icon"></span>
                </div>
                <p>Upload SIPs</p>
            </div>
        </div>
        <div class="five wide column">
            <div class="ui inline compact segment home-card" data-id="3">
                <div class="box">
                    <span class="icon icon-drive home-icon"></span>
                </div>
                <p>Manage archive store</p>
            </div>
        </div>
        <div class="five wide column">
            <div class="ui inline compact segment home-card" data-id="5">
                <div class="box">
                    <span class="icon icon-cogs home-icon"></span>
                </div>
                <p>Archive and profile settings</p>
            </div>
        </div>

        <!-- first row ends here -->

        <!-- Begin second row -->

        <div class="one wide column"></div>
        <div class="five wide column">
            <div class="ui inline compact segment home-card" data-id="4">
                <div class="box">
                    <span class="icon icon-search home-icon"></span>
                </div>
                <p>Finding aids</p>
            </div>
        </div>
        <div class="five wide column">
            <div class="ui inline compact segment home-card" data-id="6">
                <div class="box">
                    <span class="icon icon-bubbles home-icon"></span>
                </div>
                <p>How tos</p>
            </div>
        </div>
        <!-- second row ends here -->
    </div>
</article>
{% endblock %}

ingest/templates/ingest/index.html
{% load staticfiles %}
<!Doctype html>
<html>
    <head>
        <meta charset='utf-8'/>
        <title>archiva:perservation made easy</title>        
        <!-- All stylesheets -->
        <link rel="stylesheet" href="{% static 'ingest/css/semantic.css' %}" />
        <link rel="stylesheet" href="{% static 'ingest/css/icons.css' %}" />
        <link rel="stylesheet" href="{% static 'ingest/css/main.css' %}" />
    </head>
    <body>
        <header class="ui fixed menu home">
            <div class="item blue-c">
                <a href="{% url 'ingest:index' %}">
                    <h2 class="ui inverted header"><span class="icon icon-book"></span>Archiva</h2>
                </a>
            </div>
            <nav class="ui container transparent">                
                <div class="ui right item">
                    <div class="ui orange medium button"><span class="icon icon-enter"></span>signin</div>
                    <div class="ui blue medium button"><span class="icon icon-clipboard"></span>signup</div>
                </div>               
            </nav>
        </header>
         <div class="overlay"></div> 
        <!-- Billboard -->
        <section class="ui container bill bill-img">                              
            <div class="ui text-center container">
                <h1 class="ui inverted header caption">
                   Keep track of all your Undergraduate projects</h1>
                <h2>archiva makes preservation easy</h2>
                <button class="ui large primary button"><span class="icon icon-point-right"></span>Get started!</button>
            </div>
        </section>
        
        <!-- Main content -->
        <section class="ui middle">
            <div class="ui container frame">
                <div class="ui three column grid">
                    <div class="row stickyinfo">
                        <div class="column"></div>
                        <div class="column"></div>
                        <div class="column"></div>
                    </div>
                </div>   
            </div>          
        </section>
    </body>    
    <!-- Script files -->
    <script src="{% static 'ingest/js/jquery-1.11.2.min.js' %}"></script>
    <script src="{% static 'ingest/css/semantic.js' %}"></script>
    <script>
        window.onload = function() {
            var btns = document.getElementsByTagName('button');

            var toLogin = function() {
                window.location = "{% url 'ingest:login' %}"
            }

            var toSignUp = function() {
                window.location = "{% url 'ingest:signup' %}"
            }

            btns[0].addEventListener('click', toLogin, false);
        }
    </script>
</html>

ingest/templates/ingest/ingestdash.html
{% extends "ingest/homedash.html" %}
{% block controls %}
     <article class="ui relaxed divided list container">
        <a href="{% url 'ingest:homedash' user.id %}"><div class="item btn"><span class="icon icon-home"></span>Home</div></a>
        <a href="{% url 'ingest:ingestdash' user.id %}"><div class="item btn actives"><span class="icon icon-cloud-upload"></span>Ingest</div></a>
        <div class="item btn"><span class="icon icon-database"></span>Store</div>
        <div class="item btn"><span class="icon icon-search"></span>Search</div>
        <div class="item btn"><span class="icon icon-cogs"></span>Settings</div>
        <div class="item btn"><span class="icon icon-bubbles4"></span>How tos</div>
    </article>
{% endblock %}
{% block content %}

    <div>
        <div class="ingest-one">
            <div class="ui inline form">
                <div class="field">
                    <div><h2>select repository</h2></div>
                    <div class="four wide field">
                        <select name="reponame" class="ui fluid dropdown">
                            <option>Western sites</option>
                            <option>Final year project 2012</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="">
                <button id="create-repo" class="ui primary button">create repository</button>
            </div>



<div class="ui modal">
  <i class="close icon"></i>
  <div class="header">
    Create Repository
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="/images/avatar/large/chris.jpg">
    </div>
    <div class="description">
      <div class="ui header">We've auto-chosen a profile image for you.</div>
      <p>We've grabbed the following image from the <a href="https://www.gravatar.com" target="_blank">gravatar</a> image associated with your registered e-mail address.</p>
      <p>Is it okay to use this photo?</p>
    </div>
  </div>
  <div class="actions">
    <div class="ui black deny button">
      Cancel
    </div>
    <div class="ui positive right labeled icon button">
      Done
      <i class="checkmark icon"></i>
    </div>
  </div>
</div>




            </div>
    </div>
{% endblock %}

ingest/templates/ingest/login.html
{% load staticfiles %}
<!Doctype html>
<html>
    <head>
        <meta charset='utf-8'/>
        <title>archiva:perservation made easy</title>        
        <!-- All stylesheets -->
        <link rel="stylesheet" href="{% static 'ingest/css/semantic.css' %}" />
        <link rel="stylesheet" href="{% static 'ingest/css/icons.css' %}" />
        <link rel="stylesheet" href="{% static 'ingest/css/main.css' %}" />
         <link rel="stylesheet" href="{% static 'ingest/css/reg.css' %}" />
    </head>
    <body class="body-w">
        <!-- header and navigation area 
        <header class="ui fixed menu">
             <div class="ui item bar">
                 <a href="{% url 'ingest:index' %}">
                     <h2 class="ui header"><span class="icon icon-book "></span>Archiva</h2>
                 </a>
              </div>
        </header>-->
        
        <header class="ui container formhead slim">
            <a href="{% url 'ingest:index' %}">
                <h2><span class="icon icon-book"></span>&nbsp;Archiva</h2>
            </a>
        </header>
        <!-- -->
        <section class="ui container mediumwidth">
             <div class="ui three column grid c">
                <div class="row strip">
                    <div class="column dblue"></div>
                    <div class="column lgray"></div>
                    <div class="column dblue"></div>
                </div>
            </div>
            <header class="ui container formhead">
                <h1>Login</h1>
            </header>
            <form class="ui equal width form fluid signup" action="{% url 'ingest:login' %}" method="POST">
                {% csrf_token %}
                 <div class="fourteen wide field"> 
                     <label for="firstname">Username</label>        
                     <input type="text" name="username" placeholder="johndoe@gmail.com" />
                </div>
                 <div class="fourteen wide field"> 
                     <label for="firstname">Password</label>
                     <input type="password" name="password" placeholder="********" />
                </div>
                <div class="sixteen wide field">
                     <div>
                        <span style="color: red">{{ error }}</span>
                    </div>
                    <button class="ui large submit button" type="submit" name="login" value="logged">
                        <span class="icon icon-enter"></span>Sign in
                    </button>
                    <div class="new-user" style="color:deepskyblue; margin:2em auto 2em auto">
                        Don't have an account click <a href="{% url 'ingest:signup' %}"><u>here</u></a> to create one
                    </div>
                </div>
            </form>           
        </section>
        <footer class="ui container">
            miisoft corp
        </footer>
    </body>    
    <!-- Script files -->
    <script src=""></script>       
</html>

ingest/templates/ingest/repository_file_list.html
{% load staticfiles %}
<section class="ui container repo-area">
    <header class="ui four column grid">
        <div class="column"><h3><span class="icon blue icon-folder-open folder-small"></span>{{ repository.name }}</h3></div>
        <div class="column">
            <div class="ui teal huge label">
              Size
              <div class="detail">{{ repository.repo_size|filesizeformat }}</div>
            </div>
        </div>
        <div class="column"></div>
        <div class="column">
            <div class="ui right floated blue buttons">
                <button class="ui button"><span class="icon icon-arrow-left2"></span></button>
                <button class="ui button"><i class="grid layout icon"></i></button>
                <button class="ui button"><i class="list layout icon"></i></button>
            </div>
        </div>
    </header>
    <div class="ui section divider"></div>

    <section class="ui container table-view">
        <table class="content-table">
            <tbody>
            {% for f in files %}
                <tr>
                    <td><span class="icon icon-file-picture"></span></td>
                    <td>{{ f.content_name }}</td>
                    {% for k, v in meta.items %}
                      {% if f.content_name == k %}
                        <td>{{ v.file_size|filesizeformat }}</td>
                        <td>{{ v.file_type }}</td>
                        <td>{{ v.date_uploaded }}</td>
                        <td>{{ v.meta_tags }}</td>
                      {% endif %}
                    {% endfor %}
                    <td><a href="{{ f.file.url }}"><span class="icon icon-download3"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>


    <!-- Icon View -->
    <section class="ui container">
        <div class="">

        </div>
    </section>
</section>

ingest/templates/ingest/search.html
{% load staticfiles %}
<section class="ui container repo-area">
   <header class="ui four column grid">
        <div class="column"><h2>Search</h2></div>
        <div class="column">
        </div>
        <div class="column"></div>
        <div class="column">
            <div class="ui right floated">
               <div class="ui len search">
                  <input class="prompt" type="text" placeholder="search" autocomplete="off">
                  <div class="results"></div>
               </div>
            </div>
        </div>
    </header>
    <div class="ui section divider"></div>
</section>
<script src="{% static 'ingest/js/search.js' %}"></script>

ingest/templates/ingest/signup.html
{% load staticfiles %}
<!Doctype html>
<html>
    <head>
        <meta charset='utf-8'/>
        <title>archiva:perservation made easy</title>        
        <!-- All stylesheets -->
        <link rel="stylesheet" href="{% static 'ingest/css/semantic.css' %}" />
        <link rel="stylesheet" href="{% static 'ingest/css/icons.css' %}" />
        <link rel="stylesheet" href="{% static 'ingest/css/main.css' %}" />
        <link rel="stylesheet" href="{% static 'ingest/css/reg.css' %}" />
    </head>
    <body class="body-w">
        <!-- header and navigation area 
        <header class="ui fixed menu">
             <div class="ui item bar">
                 <a href="{% url 'ingest:index' %}">
                     <h2 class="ui header"><span class="icon icon-book "></span>Archiva</h2>
                 </a>
              </div>
        </header>-->
        
        <header class="ui container formhead slim">
            <a href="{% url 'ingest:index' %}">
                <h2><span class="icon icon-book"></span>&nbsp;Archiva</h2>
            </a>
        </header>
        <!-- -->
        <section class="ui container mediumwidth">            
            <div class="ui three column grid c">
                <div class="row strip">
                    <div class="column dblue"></div>
                    <div class="column lgray"></div>
                    <div class="column dblue"></div>
                </div>
            </div>
                       
            <header class="ui container formhead">
                <h1>Signup</h1>
            </header>
            <form class="ui equal width form fluid signup" action="{% url 'ingest:signup' %}" method="post">
                {% csrf_token %}
                <div class="fourteen wide field"> 
                     <label for="firstname">Firstname</label>        
                     <input type="text" name="firstname" placeholder="Okoye" />
                </div>
                <div class="fourteen wide field">
                     <label for="lastname">Lastname</label>
                     <input type="text" name="lastname" placeholder="Michael" />
                </div>
                <div class="fourteen wide field">
                     <label for="interest">Field of interest</label>
                     <input type="text" name="interest" placeholder="Enter field of interest" />
                </div>
                <div class="fourteen wide field">
                     <label for="email">Email</label>
                     <input type="email" name="email" placeholder="m@cheeky.com" />
                </div>
                <div class="fourteen wide field">
                     <label for="password">Password</label>
                     <input type="password" name="password" placeholder="********" />
                </div>
                <div class="fourteen wide field">
                     <label for="confirm password">Confirm password</label>
                     <input type="password" name="cpassword" placeholder="********" />
                </div>
                <div class="sixteen wide field">
                    <button class="ui large submit button" type="submit" name="login" value="logged">Signup</button>
                    <div>
                        <span style="color: red">{{ error }}</span>
                    </div>
                </div>
            </form>  
            <br/><br/>
        </section>
        <footer class="ui container">
            miisoft corp
        </footer>
    </body>    
    <!-- Script files -->
    <script src=""></script>       
</html>

ingest/templates/ingest/uploaded.html
<section>
    {% if context %}
        {% for k, v in context.items %}
            <li>{{ k }}: {{ v }}</li>
        {% endfor %}
    {% endif %}
</section>